import { Button } from "@mui/material";
import {
  AdminPanelSettingsOutlined,
  SecurityOutlined,
  LockOpenOutlined,
} from "@mui/icons-material";
import { useTheme } from "@emotion/react";

export const rows = [
  {
    id: 1,
    registrarId: 123512,
    name: "Jon Snow",
    age: 35,
    phone: "(665)121-5454",
    email: "jonsnow@gmail.com",
    address: "09 Ridgewood St.",
    city: "New York",
    zipCode: 10001,
  },
  {
    id: 2,
    registrarId: 123512,
    name: "Cersei Lannister",
    age: 42,
    phone: "(421)314-2288",
    email: "cerseilannister@gmail.com",
    address: "12 Wilshire Blvd.",
    city: "New York",
    zipCode: 13151,
  },
  {
    id: 3,
    registrarId: 4132513,
    name: "Jaime Lannister",
    age: 45,
    phone: "(422)982-6739",
    email: "jaimelannister@gmail.com",
    address: "33 Sunset Dr.",
    city: "New York",
    zipCode: 87281,
  },
  {
    id: 4,
    registrarId: 123512,
    name: "Anya Stark",
    age: 16,
    phone: "(921)425-6742",
    email: "anyastark@gmail.com",
    address: "15 Maple Ave.",
    city: "New York",
    zipCode: 15551,
  },
  {
    id: 5,
    registrarId: 123512,
    name: "Daenerys Targaryen",
    age: 31,
    phone: "(421)445-1189",
    email: "daenerystargaryen@gmail.com",
    address: "11 Ocean St.",
    city: "Texas",
    zipCode: 14215,
  },
  {
    id: 6,
    registrarId: 123512,
    name: "Ever Melisandre",
    age: 150,
    phone: "(232)545-6483",
    email: "evermelisandre@gmail.com",
    address: "12 Highland Rd.",
    city: "Essex",
    zipCode: 10001,
  },
  {
    id: 7,
    registrarId: 123512,
    name: "Ferrara Clifford",
    age: 44,
    phone: "(543)124-0123",
    email: "ferraraclifford@gmail.com",
    address: "22 Walnut St.",
    city: "Evanston",
    zipCode: 51523,
  },
  {
    id: 8,
    registrarId: 512315,
    name: "Rossini Frances",
    age: 36,
    phone: "(222)444-5555",
    email: "rossinifrances@gmail.com",
    address: "17 Lincoln St.",
    city: "Essex",
    zipCode: 44215,
  },
  {
    id: 9,
    registrarId: 928397,
    name: "Harvey Roxie",
    age: 65,
    phone: "(444)555-6239",
    email: "harveyroxie@gmail.com",
    address: "51 Main St.",
    city: "Colorado",
    zipCode: 111234,
  },
];

export const columns = [
  {
    field: "id",
    headerName: "ID",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "registrarId",
    headerName: "Registrar ID",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "age",
    headerName: "Age",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "phone",
    headerName: "Phone",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "address",
    headerName: "Address",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "city",
    headerName: "City",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "zipCode",
    headerName: "Zip Code",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
];
